load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["fstree.go"],
    importpath = "github.com/smukherj1/fs-tree/pkg/fstree",
    visibility = ["//visibility:public"],
)
